### ISSUE TITLE
7Import does not work on python 3.6

### ISSUE THREAD

**Issue by sharky1337** [jquast/telnetlib3#32]
Hello, 

I want to test your library, but I'm not able to import it.

> Python 3.7.0 (default, Oct 16 2018, 19:43:19)
[Clang 10.0.0 (clang-1000.11.45.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio, telnetlib3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/telnetlib3/__init__.py", line 3, in <module>
    from .server_base import *      # noqa
  File "/usr/local/lib/python3.7/site-packages/telnetlib3/server_base.py", line 8, in <module>
    from .stream_writer import (TelnetWriter, TelnetWriterUnicode)
  File "/usr/local/lib/python3.7/site-packages/telnetlib3/stream_writer.py", line 9, in <module>
    from . import slc
  File "/usr/local/lib/python3.7/site-packages/telnetlib3/slc.py", line 4, in <module>
    from .accessories import eightbits, name_unicode
  File "/usr/local/lib/python3.7/site-packages/telnetlib3/accessories.py", line 94
    task = asyncio.async
                       

> ^

I'm running python 3.7.0 on MacOS Mojave

**Comment by jquast** [comment]
this is fixed in release 1.0.1 being pushed to pypi
