### ISSUE TITLE
bin/telnet-client should warn when stdout is ascii codec ?

### ISSUE THREAD

**Issue by jquast** [jquast/telnetlib3#4]
:$$$: .,g

2014-03-03 11:03:12,205 ERROR base_events.py:677 Exception in callback <bound method _SelectorSocketTransport._read_ready of <asyncio.selector_events._SelectorSocketTransport object at 0x7f9578c1bc10>>()
handle: Handle(<bound method _SelectorSocketTransport._read_ready of <asyncio.selector_events._SelectorSocketTransport object at 0x7f9578c1bc10>>, ())
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/asyncio/events.py", line 39, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.3/site-packages/asyncio/selector_events.py", line 458, in _read_ready
    self._protocol.data_received(data)
  File "/usr/lib/python3.3/site-packages/telnetlib3/client.py", line 424, in data_received
    self.shell.feed_byte(byte)
  File "/usr/lib/python3.3/site-packages/telnetlib3/conio.py", line 83, in feed_byte
    self.write(ucs)
  File "/usr/lib/python3.3/site-packages/telnetlib3/conio.py", line 130, in write
    self.stream_out.write(string)
UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 0: ordinal not in range(128)

**Comment by jquast** [comment]
i'm not sure this is relevant now that default encoding output is utf8
