### ISSUE TITLE
Cannot install with pip 6.0.8, python 3.4.3, OS X 10.10.2

### ISSUE THREAD

**Issue by sethb0** [jquast/telnetlib3#6]
Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/tp/sf8pkx4j49j9gf3c1bxntffr0000gn/T/pip-build-r1bjhsa2/telnetlib3/setup.py", line 28, in <module>
        install_requires = [str(req.req) for req in requirements]
      File "/private/var/folders/tp/sf8pkx4j49j9gf3c1bxntffr0000gn/T/pip-build-r1bjhsa2/telnetlib3/setup.py", line 28, in <listcomp>
        install_requires = [str(req.req) for req in requirements]
      File "/Users/sethb/.virtualenvs/eight/lib/python3.4/site-packages/pip/req/req_file.py", line 19, in parse_requirements
        "parse_requirements() missing 1 required keyword argument: "
    TypeError: parse_requirements() missing 1 required keyword argument: 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/private/var/folders/tp/sf8pkx4j49j9gf3c1bxntffr0000gn/T/pip-build-r1bjhsa2/telnetlib3/setup.py", line 28, in <module>
    
        install_requires = [str(req.req) for req in requirements]
    
      File "/private/var/folders/tp/sf8pkx4j49j9gf3c1bxntffr0000gn/T/pip-build-r1bjhsa2/telnetlib3/setup.py", line 28, in <listcomp>
    
        install_requires = [str(req.req) for req in requirements]
    
      File "/Users/sethb/.virtualenvs/eight/lib/python3.4/site-packages/pip/req/req_file.py", line 19, in parse_requirements
    
        "parse_requirements() missing 1 required keyword argument: "
    
    TypeError: parse_requirements() missing 1 required keyword argument: 'session'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/tp/sf8pkx4j49j9gf3c1bxntffr0000gn/T/pip-build-r1bjhsa2/telnetlib3

**Comment by jquast** [comment]
Sorry about missing this issue, I think I'm on so many projects the firehose of e-mails passes me by, telnetlib3 gets my attention for the next week so I'll close this issue shortly when this is addressed on pypi

**Comment by jquast** [comment]
0.2.4 release to pypi, this should work now. Thank you for the report !!
