### ISSUE TITLE
Script telnetlib3-client not working

### ISSUE THREAD

**Issue by Timsbim** [jquast/telnetlib3#69]
Whenever I'm trying to run the `telnetlib3-client` script, e.g. `telnetlib3-client 127.0.0.1`, I get the following error:
```python
Traceback (most recent call last):
  File "/Users/timus/Coding/envs/py3.11/bin/telnetlib3-client", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/timus/Coding/envs/py3.11/lib/python3.11/site-packages/telnetlib3/client.py", line 450, in main
    asyncio.run(run_client())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/timus/Coding/envs/py3.11/lib/python3.11/site-packages/telnetlib3/client.py", line 370, in run_client
    key_values=accessories.repr_mapping(kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timus/Coding/envs/py3.11/lib/python3.11/site-packages/telnetlib3/accessories.py", line 92, in repr_mapping
    "=".join(f"{key}={shlex.quote(value)}" for key, value in mapping.items())
  File "/Users/timus/Coding/envs/py3.11/lib/python3.11/site-packages/telnetlib3/accessories.py", line 92, in <genexpr>
    "=".join(f"{key}={shlex.quote(value)}" for key, value in mapping.items())
                      ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shlex.py", line 329, in quote
    if _find_unsafe(s) is None:
       ^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'int'
```
This happens on Linux as well as macOS, for CPython 3.8 - 3.11.

**Comment by jquast** [comment]
Closed by release of 2.0.1 https://telnetlib3.readthedocs.io/en/master/history.html#history
