### ISSUE TITLE
installtion fails with pip > 1.5

### ISSUE THREAD

**Issue by ckauhaus** [jquast/telnetlib3#8]
With pip 1.5.6, package installation runs smoothly:

```
$ bin/pip-1.5.6 install telnetlib3 
Downloading/unpacking telnetlib3
  Downloading telnetlib3-0.2.3.tar.gz (96kB): 96kB downloaded
  Running setup.py (path:/home/ckauhaus/code/backy/build/telnetlib3/setup.py) egg_info for package telnetlib3
    
Requirement already satisfied (use --upgrade to upgrade): asyncio in ./lib/python3.4/site-packages (from telnetlib3)
Installing collected packages: telnetlib3
  Running setup.py install for telnetlib3
    changing mode of build/scripts-3.4/telnet-client from 644 to 755
    changing mode of build/scripts-3.4/telnet-server from 644 to 755
    changing mode of build/scripts-3.4/telnet-talker from 644 to 755
    
    changing mode of /home/ckauhaus/code/backy/bin/telnet-client to 755
    changing mode of /home/ckauhaus/code/backy/bin/telnet-server to 755
    changing mode of /home/ckauhaus/code/backy/bin/telnet-talker to 755
Successfully installed telnetlib3
```

However, using newer pip versions just spit out installation errors due to an missing keyword argument in parse_requirements():

```
$ bin/pip install telnetlib3
Collecting telnetlib3
  Using cached telnetlib3-0.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-rtq64401/telnetlib3/setup.py", line 28, in <module>
        install_requires = [str(req.req) for req in requirements]
      File "/tmp/pip-build-rtq64401/telnetlib3/setup.py", line 28, in <listcomp>
        install_requires = [str(req.req) for req in requirements]
      File "/home/ckauhaus/code/backy/lib/python3.4/site-packages/pip/req/req_file.py", line 72, in parse_requirements
        "parse_requirements() missing 1 required keyword argument: "
    TypeError: parse_requirements() missing 1 required keyword argument: 'session'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rtq64401/telnetlib3
```

I'm using Python 3.4.1.

**Comment by jquast** [comment]
will fix shortly thanks!

**Comment by ckauhaus** [comment]
Works now on fd39251

**Comment by jquast** [comment]
0.2.4 release to pypi, thanks for the test report.  I only just recently picked maintenance up on this project, sorry for the long hesitations.  If you'd like to propose any changes or discover any bugs, please do not hesitate to file issues or pull requests, thank you again!
